import React, { useEffect, useMemo, useState } from 'react';
import { Routes, Route, Link, useNavigate, useParams, Navigate } from 'react-router-dom';
import api from './api';

const nav = [
  ['/dashboard','Dashboard'], ['/resume','Resume'], ['/jobs','Jobs'], ['/interview/setup','Mock Interview'],
  ['/interviews','History'], ['/coding','Coding'], ['/system-design','System Design'], ['/coach','AI Coach'],
  ['/analytics','Analytics'], ['/profile','Profile']
];

function Shell({children}:{children:React.ReactNode}) {
  const n=useNavigate();
  return <div className="app"><aside><h2>InterviewAce<span>AI</span></h2>{nav.map(([p,t])=><Link key={p} to={p}>{t}</Link>)}<button onClick={()=>{localStorage.removeItem('token');n('/login')}}>Logout</button></aside><main><header>AI-powered interview preparation</header>{children}</main></div>;
}
function Protected({children}:{children:React.ReactNode}) { return localStorage.getItem('token')?<Shell>{children}</Shell>:<Navigate to="/login"/>; }
function Landing(){return <div className="landing"><nav><b>InterviewAceAI</b><Link to="/login">Login</Link></nav><section><p className="eyebrow">AI INTERVIEW PREPARATION</p><h1>Practice Smarter.<br/><span>Interview Better.</span><br/>Get Hired.</h1><p>Resume intelligence, job matching, adaptive mock interviews, coding practice and measurable feedback in one workspace.</p><Link className="btn" to="/register">Start Practicing</Link></section></div>}
function Auth({register=false}:{register?:boolean}){const [f,setF]=useState({name:'',email:'',password:''});const [e,setE]=useState('');const n=useNavigate();async function go(x:React.FormEvent){x.preventDefault();try{const r=await api.post(`/auth/${register?'register':'login'}`,f);localStorage.setItem('token',r.data.data.token);n('/dashboard')}catch(err:any){setE(err.response?.data?.error?.message||'Request failed')}}return <div className="auth"><form className="card" onSubmit={go}><p className="eyebrow">INTERVIEWACEAI</p><h2>{register?'Create your account':'Welcome back'}</h2>{register&&<input required placeholder="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input required placeholder="Email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required minLength={8} placeholder="Password (8+ characters)" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{e&&<p className="error">{e}</p>}<button className="btn">{register?'Register':'Login'}</button><p><Link to={register?'/login':'/register'}>{register?'Already have an account? Login':'Create an account'}</Link></p></form></div>}

function Dashboard(){const [d,setD]=useState<any>({});useEffect(()=>{api.get('/analytics/summary').then(x=>setD(x.data.data)).catch(()=>{})},[]);return <><div className="title"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Dashboard</h1><p className="muted">Track your preparation and choose your next practice session.</p></div><Link className="btn" to="/interview/setup">Start interview</Link></div><div className="stats">{[['Readiness',d.readiness||0],['Interviews',d.interviewsCompleted||0],['Questions',d.questionsAnswered||0],['Avg score',d.averageScore||0]].map(([a,b])=><div className="card stat" key={String(a)}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="grid two"><div className="card"><h3>Preparation path</h3><div className="steps"><span>1 Resume</span><span>2 Target job</span><span>3 Mock interview</span><span>4 Review report</span></div></div><div className="card"><h3>Quick practice</h3><p className="muted">Strengthen communication, coding and system-design skills with focused sessions.</p><div className="actions"><Link className="chip" to="/coding">Coding</Link><Link className="chip" to="/system-design">System Design</Link><Link className="chip" to="/coach">AI Coach</Link></div></div></div></>}

function Resume(){const [file,setFile]=useState<File>();const [text,setText]=useState('');const [r,setR]=useState<any>();const [err,setErr]=useState('');async function analyze(){setErr('');try{const f=new FormData();if(file)f.append('resume',file);if(text)f.append('text',text);const x=await api.post('/resumes/analyze',f);setR(x.data.data)}catch(e:any){setErr(e.response?.data?.error?.message||'Resume analysis failed')}}return <><div className="title"><div><p className="eyebrow">DOCUMENT INTELLIGENCE</p><h1>Resume Analyzer</h1></div></div><div className="grid two"><div className="card"><h3>Upload resume</h3><p className="muted">PDF, DOCX or TXT up to 5 MB. TXT works immediately; PDF/DOCX require extracted text in the current parser configuration.</p><input type="file" accept=".pdf,.docx,.txt" onChange={e=>setFile(e.target.files?.[0])}/><textarea rows={8} placeholder="Optional: paste resume text here for PDF/DOCX analysis" value={text} onChange={e=>setText(e.target.value)}/><button className="btn" onClick={analyze}>Analyze resume</button>{err&&<p className="error">{err}</p>}</div>{r&&<div className="card"><h3>Resume report</h3><div className="score">{r.analysis?.resumeScore||0}<small>/100</small></div><div className="stats compact">{[['ATS',r.analysis?.atsScore],['Skills',r.analysis?.skills?.length||0],['Recommendations',r.analysis?.recommendations?.length||0]].map(([a,b])=><div className="mini" key={String(a)}><small>{a}</small><strong>{b}</strong></div>)}</div><h4>Skills</h4><div className="chips">{(r.analysis?.skills||[]).map((s:string)=><span className="chip" key={s}>{s}</span>)}</div><h4>Recommendations</h4><ul>{(r.analysis?.recommendations||[]).map((s:string)=><li key={s}>{s}</li>)}</ul></div>}</div></>}

function Jobs(){const [text,setText]=useState('');const [r,setR]=useState<any>();const [history,setHistory]=useState<any[]>([]);const [err,setErr]=useState('');useEffect(()=>{api.get('/jobs').then(x=>setHistory(x.data.data||[])).catch(()=>{})},[]);async function analyze(){setErr('');try{setR((await api.post('/jobs/analyze',{text})).data.data)}catch(e:any){setErr(e.response?.data?.error?.message||'Job analysis failed')}}return <><div className="title"><div><p className="eyebrow">JOB INTELLIGENCE</p><h1>Jobs & Match</h1></div></div><div className="grid two"><div className="card"><h3>Analyze a target role</h3><input placeholder="Job title (optional)"/><input placeholder="Company (optional)"/><textarea rows={12} minLength={30} placeholder="Paste the job description (30+ characters)" value={text} onChange={e=>setText(e.target.value)}/><button className="btn" onClick={analyze}>Analyze & match</button>{err&&<p className="error">{err}</p>}</div><div>{r?<div className="card"><p className="eyebrow">MATCH SCORE</p><div className="score">{r.match?.score||0}<small>%</small></div><h3>Strengths</h3><div className="chips">{(r.match?.strengths||[]).map((x:string)=><span className="chip" key={x}>{x}</span>)}</div><h3>Skill gaps</h3><ul>{(r.match?.skillGaps||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></div>:<div className="card"><h3>Previous analyses</h3>{history.length?<ul className="history">{history.slice(0,6).map(x=><li key={x._id}><b>{x.title||'Untitled role'}</b><span>{x.match?.score||0}% match</span></li>)}</ul>:<p className="muted">No job analyses yet.</p>}</div>}</div></div></>}

function Setup(){const [mode,setMode]=useState('mixed');const [difficulty,setDifficulty]=useState('medium');const [role,setRole]=useState('Software Engineer');const n=useNavigate();async function start(){const r=await api.post('/interviews',{mode,difficulty,targetRole:role});n(`/interview/${r.data.data._id}`)}return <div className="card narrow"><p className="eyebrow">ADAPTIVE PRACTICE</p><h1>Mock Interview Setup</h1><p className="muted">Configure a five-question session and receive feedback after every answer.</p><label>Target role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Interview mode<select value={mode} onChange={e=>setMode(e.target.value)}>{['mixed','technical','hr','behavioral','coding','system-design','resume-based'].map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['easy','medium','hard','expert'].map(x=><option key={x}>{x}</option>)}</select></label><button className="btn" onClick={start}>Start interview</button></div>}
function Interview(){const {id}=useParams();const [i,setI]=useState<any>();const [a,setA]=useState('');const [f,setF]=useState<any>();const [err,setErr]=useState('');async function load(){try{setI((await api.get(`/interviews/${id}`)).data.data)}catch(e:any){setErr(e.response?.data?.error?.message||'Unable to load interview')}}useEffect(()=>{void load()},[id]);if(err)return <div className="card error">{err}</div>;if(!i)return <div className="card">Loading interview…</div>;if(i.status==='completed')return <div className="card"><p className="eyebrow">COMPLETED INTERVIEW</p><h1>Interview Report</h1><div className="score">{i.report?.overall||0}<small>/100</small></div><div className="grid two"><div><h3>Strengths</h3><ul>{(i.report?.strengths||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></div><div><h3>Improve next</h3><ul>{(i.report?.weaknesses||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></div></div><Link className="btn" to="/dashboard">Back to dashboard</Link></div>;const q=i.questions[i.currentIndex];async function submit(){if(!a.trim())return;try{const r=await api.post(`/interviews/${id}/answer`,{questionId:q.id,answer:a});setF(r.data.data.evaluation);setA('');await load()}catch(e:any){setErr(e.response?.data?.error?.message||'Answer submission failed')}}async function finish(){await api.post(`/interviews/${id}/complete`);await load()}return <div className="card"><div className="progress"><span>Question {i.currentIndex+1} of 5</span><b>{Math.min(100,Math.round((i.currentIndex/5)*100))}%</b></div><p className="eyebrow">{i.type} · {i.difficulty} · {i.targetRole}</p><h2>{q?.question}</h2><textarea rows={12} value={a} onChange={e=>setA(e.target.value)} placeholder="Explain your answer with context, approach, trade-offs and result…"/><button className="btn" onClick={submit}>Submit answer</button>{f&&<div className="feedback"><h3>AI evaluation: {f.score}/100</h3><p><b>Strengths:</b> {f.strengths?.join(' · ')}</p><p><b>Improve:</b> {f.weaknesses?.join(' · ')}</p>{f.improvedAnswer&&<p><b>Better structure:</b> {f.improvedAnswer}</p>}</div>}{i.currentIndex>=5&&<button className="btn secondary" onClick={finish}>Generate final report</button>}{err&&<p className="error">{err}</p>}</div>}

function History(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{api.get('/interviews').then(x=>setItems(x.data.data||[]))},[]);return <><div className="title"><div><p className="eyebrow">PAST PRACTICE</p><h1>Interview History</h1></div><Link className="btn" to="/interview/setup">New interview</Link></div><div className="card">{items.length?<ul className="history">{items.map(x=><li key={x._id}><div><b>{x.targetRole}</b><span>{x.type} · {x.difficulty} · {x.status}</span></div><strong>{x.overallScore??'—'}</strong><Link to={`/interview/${x._id}`}>Open</Link></li>)}</ul>:<div className="empty"><h3>No interviews yet</h3><p>Start your first mock interview to build your history.</p><Link className="btn" to="/interview/setup">Start now</Link></div>}</div></>}

function Coding(){const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState<any>();const [answer,setAnswer]=useState('');const [evaluation,setEvaluation]=useState<any>();useEffect(()=>{api.get('/practice/coding').then(x=>{setItems(x.data.data||[]);setSelected(x.data.data?.[0])})},[]);async function evaluate(){if(!selected||!answer.trim())return;const e=await api.post('/practice/evaluate',{question:selected.prompt,answer});setEvaluation(e.data.data.evaluation)}return <><div className="title"><div><p className="eyebrow">TECHNICAL PRACTICE</p><h1>Coding Lab</h1><p className="muted">Practice algorithmic reasoning and get AI feedback on your explanation or solution approach.</p></div></div><div className="coding-layout"><div className="card question-list">{items.map(x=><button className={selected?.id===x.id?'selected':''} key={x.id} onClick={()=>{setSelected(x);setEvaluation(undefined)}}><b>{x.title}</b><span>{x.difficulty} · {x.topic}</span></button>)}</div>{selected&&<div className="card"><div className="badge">{selected.difficulty}</div><h2>{selected.title}</h2><p>{selected.prompt}</p><h3>Hints</h3><ul>{selected.hints.map((h:string)=><li key={h}>{h}</li>)}</ul><textarea rows={14} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Write your solution, algorithm and complexity here…"/><button className="btn" onClick={evaluate}>Get AI feedback</button>{evaluation&&<div className="feedback"><h3>Score: {evaluation.score}/100</h3><p>{evaluation.strengths?.join(' · ')}</p><p>{evaluation.weaknesses?.join(' · ')}</p></div>}</div>}</div></>}

function SystemDesign(){const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState<any>();const [answer,setAnswer]=useState('');const [evaluation,setEvaluation]=useState<any>();useEffect(()=>{api.get('/practice/system-design').then(x=>{setItems(x.data.data||[]);setSelected(x.data.data?.[0])})},[]);async function evaluate(){if(!selected||!answer.trim())return;const e=await api.post('/practice/evaluate',{question:selected.prompt,answer});setEvaluation(e.data.data.evaluation)}return <><div className="title"><div><p className="eyebrow">ARCHITECTURE PRACTICE</p><h1>System Design</h1><p className="muted">Practice requirements, architecture, scaling and trade-offs.</p></div></div><div className="design-grid"><div className="card question-list">{items.map(x=><button className={selected?.id===x.id?'selected':''} key={x.id} onClick={()=>{setSelected(x);setEvaluation(undefined)}}><b>{x.title}</b><span>{x.level}</span></button>)}</div>{selected&&<div className="card"><h2>{selected.title}</h2><p>{selected.prompt}</p><div className="chips">{selected.focus.map((x:string)=><span className="chip" key={x}>{x}</span>)}</div><textarea rows={15} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Describe requirements, APIs, data model, architecture, scaling, failure handling and trade-offs…"/><button className="btn" onClick={evaluate}>Evaluate design</button>{evaluation&&<div className="feedback"><h3>Design score: {evaluation.score}/100</h3><p>{evaluation.strengths?.join(' · ')}</p><p>{evaluation.weaknesses?.join(' · ')}</p></div>}</div>}</div></>}

function Coach(){const [message,setMessage]=useState('');const [context,setContext]=useState('behavioral interview');const [messages,setMessages]=useState<{role:string,text:string}[]>([]);async function send(){if(!message.trim())return;const m=message;setMessages(x=>[...x,{role:'You',text:m}]);setMessage('');try{const r=await api.post('/practice/coach',{message:m,context});setMessages(x=>[...x,{role:'AI Coach',text:r.data.data.reply}])}catch(e:any){setMessages(x=>[...x,{role:'AI Coach',text:e.response?.data?.error?.message||'Coach request failed'}])}}return <><div className="title"><div><p className="eyebrow">PERSONAL COACH</p><h1>AI Coach</h1><p className="muted">Ask for help with answers, interview strategy, confidence, coding or system design.</p></div></div><div className="card"><select value={context} onChange={e=>setContext(e.target.value)}>{['behavioral interview','technical interview','resume','coding','system design','communication'].map(x=><option key={x}>{x}</option>)}</select><div className="chat">{messages.length?messages.map((m,i)=><div className={m.role==='You'?'bubble you':'bubble'} key={i}><b>{m.role}</b><p>{m.text}</p></div>):<div className="empty"><h3>What are you preparing for?</h3><p>Try: “How should I answer tell me about yourself?”</p></div>}</div><textarea rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask your coach…"/><button className="btn" onClick={send}>Ask coach</button></div></>}

function Analytics(){const [d,setD]=useState<any>();useEffect(()=>{api.get('/analytics/summary').then(x=>setD(x.data.data))},[]);return <><div className="title"><div><p className="eyebrow">PERFORMANCE</p><h1>Analytics</h1></div></div><div className="stats">{[['Readiness',d?.readiness||0],['Completed',d?.interviewsCompleted||0],['Questions',d?.questionsAnswered||0],['Average',d?.averageScore||0]].map(([a,b])=><div className="card stat" key={String(a)}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="card"><h3>Score trend</h3>{d?.trend?.length?<div className="trend">{d.trend.map((x:any)=><div key={String(x.date)}><span style={{height:`${Math.max(8,x.score)}%`}}></span><small>{x.score}</small></div>)}</div>:<div className="empty"><p>Complete interviews to see your performance trend.</p></div>}</div></>}

function Profile(){const [u,setU]=useState<any>();const [form,setForm]=useState<any>({});const [saved,setSaved]=useState('');useEffect(()=>{api.get('/users/me').then(x=>{setU(x.data.data);setForm(x.data.data?.profile||{})})},[]);async function save(){const r=await api.put('/users/me',{profile:{...form,skills:String(form.skills||'').split(',').map((x:string)=>x.trim()).filter(Boolean),goals:String(form.goals||'').split(',').map((x:string)=>x.trim()).filter(Boolean)}});setU(r.data.data);setSaved('Profile saved successfully.')}if(!u)return <div className="card">Loading profile…</div>;return <><div className="title"><div><p className="eyebrow">YOUR PROFILE</p><h1>Profile</h1><p className="muted">Keep your background and target role updated for personalized interviews.</p></div></div><div className="grid two"><div className="card"><h3>Account</h3><p><b>Name:</b> {u.name}</p><p><b>Email:</b> {u.email}</p></div><div className="card"><h3>Career profile</h3><input placeholder="Target role" value={form.targetRole||''} onChange={e=>setForm({...form,targetRole:e.target.value})}/><input placeholder="Degree" value={form.degree||''} onChange={e=>setForm({...form,degree:e.target.value})}/><input placeholder="Years of experience" type="number" value={form.yearsOfExperience??''} onChange={e=>setForm({...form,yearsOfExperience:e.target.value})}/><input placeholder="Skills, comma separated" value={Array.isArray(form.skills)?form.skills.join(', '):form.skills||''} onChange={e=>setForm({...form,skills:e.target.value})}/><textarea rows={5} placeholder="Goals" value={form.goals||''} onChange={e=>setForm({...form,goals:e.target.value})}/><button className="btn" onClick={save}>Save profile</button>{saved&&<p className="success">{saved}</p>}</div></div></>}

function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/resume" element={<Protected><Resume/></Protected>}/><Route path="/jobs" element={<Protected><Jobs/></Protected>}/><Route path="/interview/setup" element={<Protected><Setup/></Protected>}/><Route path="/interview/:id" element={<Protected><Interview/></Protected>}/><Route path="/interviews" element={<Protected><History/></Protected>}/><Route path="/coding" element={<Protected><Coding/></Protected>}/><Route path="/system-design" element={<Protected><SystemDesign/></Protected>}/><Route path="/coach" element={<Protected><Coach/></Protected>}/><Route path="/analytics" element={<Protected><Analytics/></Protected>}/><Route path="/profile" element={<Protected><Profile/></Protected>}/></Routes>}
export default App;
